version: "3.8"
services:
  backend:
    build:
      args:
        DEV_DEPS: "true"
    volumes:
      # mount app directory to allow live-reloading
      - "./backend:/app"
    user: "${RUN_AS:-0}"
    # change locally to `/app/scripts/debug` if you want to connect a pydevd debugger.
    # Set the pydevd port in the environment variable `$PYDEVD_PORT`. (default: 4567)
    command: "/app/scripts/run"
  db:
    ports:
      - "5432:5432"
  frontend:
    build:
      dockerfile: dev.dockerfile
    volumes:
      - "./frontend:/app"
    user: "${RUN_AS:-0}"
