# This is a basic workflow to help you get started with Actions

name: backend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Install dependencies
      working-directory: backend
      run: |
        pip install pipenv
        pipenv install --dev

    - name: mypy
      working-directory: backend
      run: pipenv run mypy .
  
    - name: flake8
      working-directory: backend
      run: pipenv run flake8
  
    - name: isort
      working-directory: backend
      run: pipenv run isort -c

    - name: black
      working-directory: backend
      run: pipenv run black --check .

    - name: pytest
      working-directory: backend
      run: |
        pipenv run coverage run --source=./notebook -m pytest
        pipenv run coverage xml
      
    # upload code coverage report to codecov.io
    - name: codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./backend/coverage.xml
